#!/bin/sh
make -C ../imx23-buildroot/ O=$PWD mxs-bootlets-rebuild
sudo losetup -d /dev/loop2
sudo losetup -d /dev/loop1
sudo losetup -d /dev/loop0
sudo rm mini.img
qemu-img create mini.img 128M
sudo losetup /dev/loop0 mini.img
sudo dd if=/dev/zero of=/dev/loop0 bs=1024 count=1024
sudo fdisk /dev/loop0 <<EOF
n
p
1

+16M
t
53

n
p
2

p

w
EOF
sudo losetup -o 1048576 /dev/loop1 /dev/loop0
sudo losetup -o 17825792 /dev/loop2 /dev/loop0
#sudo mkfs.ext2 /dev/loop1
sudo dd if=images/imx23_olinuxino_dev_linux.sb bs=512 of=/dev/loop1 seek=4
sudo dd if=images/rootfs.ext4 of=/dev/loop2 bs=512
sudo resize2fs /dev/loop2
sudo fsck.ext4 -f -v /dev/loop2

mkdir ../mnt
sudo mount -t ext4 /dev/loop2 ../mnt
sudo mkdir ../mnt/tests
sudo cp ../imx23-buildroot/misc/satie_gymnopedie.mid ../mnt/tests/
sudo cp ../imx23-buildroot/misc/tim_gm_6mb.sf2 ../mnt/tests/
sudo cp ../imx23-buildroot/misc/timidity.cfg ../mnt/tests/
sudo umount ../mnt
